{{- if .Values.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-load-balancer
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
{{- end }}
spec:
  type: "LoadBalancer"
  ports:
    - port: {{ .Values.properties.httpPort }}
      name: http
    - port: {{ .Values.properties.httpsPort }}
      name: https
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
